apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: apr1-updated-docs-5
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jdubrick-ai/apr1-updated-docs-5:96852bfe738ad12bf4254250b7fb614e1e2d601b@sha256:9ae421f8749f1afe8d86f928e37464149934b2826b46a7254ad19ff45b29e44c # use pre-built to bootstrap
          name: app-inference
