apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  rhtap/gitops: apr1-updated-docs-5
  janus-idp.io/tekton: apr1-updated-docs-5
  backstage.io/kubernetes-id: apr1-updated-docs-5
  backstage.io/kubernetes-namespace: rhdh-app
  app.kubernetes.io/part-of: apr1-updated-docs-5
resources:
  - application-dev.yaml