apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  argocd/app-name: apr1-updated-docs-5
  janus-idp.io/tekton: apr1-updated-docs-5
  backstage.io/kubernetes-id: apr1-updated-docs-5
  backstage.io/kubernetes-namespace: rhdh-app
  app.kubernetes.io/part-of: apr1-updated-docs-5
resources:
  - initialize-namespace/
  - deployment-model-server.yaml
  - service-model-server.yaml
  - deployment.yaml
  - route.yaml
  - service.yaml
  - model-config.yaml
