apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: apr1-updated-docs-5
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: apr1-updated-docs-5
  name: apr1-updated-docs-5
spec:
  ports:
    - port: 8501
      protocol: TCP
      targetPort: 8501
  selector:
    app.kubernetes.io/instance: apr1-updated-docs-5
