apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: apr1-updated-docs-5-database
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: apr1-updated-docs-5-database
  name: apr1-updated-docs-5-database
spec:
  ports:
    - port: 
      protocol: TCP
      targetPort: 
  selector:
    app.kubernetes.io/instance: apr1-updated-docs-5-database
